all:
	g++ NAS_emulator.cpp Net_stuff.cpp Requesthandler.cpp Disk.cpp Box.cpp Snapshot.cpp system_initialize.cpp interior_formats.cpp Coding.cpp Socketinteractions.cpp global_variable_and_constants.cpp -pthread -std=c++11 -o server
